//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.0.30319.1.
// 
namespace Vallen
{

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class requestForPayment {
    
    private requestForPaymentReferenceIdentification[] orderIdentificationField;
    
    private requestForPaymentCurrency currencyField;
    
    private requestForPaymentConcepto[] conceptosField;
    
    private string typeField;
    
    private string contentVersionField;
    
    private string documentStructureVersionField;
    
    private requestForPaymentDocumentStatus documentStatusField;
    
    private System.DateTime deliveryDateField;
    
    private bool deliveryDateFieldSpecified;
    
    public requestForPayment() {
        this.typeField = "SimpleInvoiceType";
        this.contentVersionField = "1.3.1";
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlArrayItemAttribute("referenceIdentification", IsNullable=false)]
    public requestForPaymentReferenceIdentification[] orderIdentification {
        get {
            return this.orderIdentificationField;
        }
        set {
            this.orderIdentificationField = value;
        }
    }
    
    /// <comentarios/>

    public requestForPaymentCurrency currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Concepto", IsNullable=false)]
    public requestForPaymentConcepto[] Conceptos {
        get {
            return this.conceptosField;
        }
        set {
            this.conceptosField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
   // [System.ComponentModel.DefaultValueAttribute("SimpleInvoiceType")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
   // [System.ComponentModel.DefaultValueAttribute("1.3.1")]
    public string contentVersion {
        get {
            return this.contentVersionField;
        }
        set {
            this.contentVersionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string documentStructureVersion {
        get {
            return this.documentStructureVersionField;
        }
        set {
            this.documentStructureVersionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public requestForPaymentDocumentStatus documentStatus {
        get {
            return this.documentStatusField;
        }
        set {
            this.documentStatusField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime deliveryDate {
        get {
            return this.deliveryDateField;
        }
        set {
            this.deliveryDateField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeliveryDateSpecified {
        get {
            return this.deliveryDateFieldSpecified;
        }
        set {
            this.deliveryDateFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class requestForPaymentReferenceIdentification {
    
    private requestForPaymentReferenceIdentificationType typeField;
    
    private string valueField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public requestForPaymentReferenceIdentificationType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum requestForPaymentReferenceIdentificationType {
    
    /// <comentarios/>
    ON,
    
    /// <comentarios/>
    CS,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]

public partial class requestForPaymentCurrency {
    [XmlAttribute("xml:space")]
   // public string SpacePreserve = "preserve";

    private string valueField;
    private requestForPaymentCurrencyCurrencyISOCode currencyISOCodeField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public requestForPaymentCurrencyCurrencyISOCode currencyISOCode {
        get {
            return this.currencyISOCodeField;
        }
        set {
            this.currencyISOCodeField = value;
        }
    }
    [System.Xml.Serialization.XmlText]
    //[System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum requestForPaymentCurrencyCurrencyISOCode {
    
    /// <comentarios/>
    MXN,
    
    /// <comentarios/>
    XEU,
    
    /// <comentarios/>
    USD,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class requestForPaymentConcepto {
    
    private decimal cantidadField;
    
    private string articuloField;
    
    private string destinoField;
    
    private decimal valorUnitarioField;
    
    private decimal importeField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal cantidad {
        get {
            return this.cantidadField;
        }
        set {
            this.cantidadField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string articulo {
        get {
            return this.articuloField;
        }
        set {
            this.articuloField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string destino {
        get {
            return this.destinoField;
        }
        set {
            this.destinoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal valorUnitario {
        get {
            return this.valorUnitarioField;
        }
        set {
            this.valorUnitarioField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal importe {
        get {
            return this.importeField;
        }
        set {
            this.importeField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum requestForPaymentDocumentStatus {
    
    /// <comentarios/>
    ORIGINAL,
    
    /// <comentarios/>
    COPY,
    
    /// <comentarios/>
    REEMPLAZA,
    
    /// <comentarios/>
    DELETE,
}
}
