//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Schema;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ahmsa.com/xsd/AddendaAHM1")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ahmsa.com/xsd/AddendaAHM1", IsNullable=false)]
public partial class AddendaAHM {

    [XmlAttribute("schemaLocation", Namespace = XmlSchema.InstanceNamespace)]
    public string xsiSchemaLocation = "http://www.ahmsa.com/xsd/AddendaAHM1 http://www.ahmsa.com/xsd/AddendaAHM1/AddendaAHM.xsd";
    
    private AddendaAHMDocumento documentoField;
    
    private string versionField;
    
    /// <remarks/>
    public AddendaAHMDocumento Documento {
        get {
            return this.documentoField;
        }
        set {
            this.documentoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ahmsa.com/xsd/AddendaAHM1")]
public partial class AddendaAHMDocumento {
    
    private AddendaAHMDocumentoEncabezado encabezadoField;
    
    private AddendaAHMDocumentoDetalle detalleField;
    
    private AddendaAHMDocumentoAnexos[] anexosField;
    
    private string tipoField;
    
    private string claseField;
    
    /// <remarks/>
    public AddendaAHMDocumentoEncabezado Encabezado {
        get {
            return this.encabezadoField;
        }
        set {
            this.encabezadoField = value;
        }
    }
    
    /// <remarks/>
    public AddendaAHMDocumentoDetalle Detalle {
        get {
            return this.detalleField;
        }
        set {
            this.detalleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Anexos")]
    public AddendaAHMDocumentoAnexos[] Anexos {
        get {
            return this.anexosField;
        }
        set {
            this.anexosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Tipo {
        get {
            return this.tipoField;
        }
        set {
            this.tipoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Clase {
        get {
            return this.claseField;
        }
        set {
            this.claseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ahmsa.com/xsd/AddendaAHM1")]
public partial class AddendaAHMDocumentoEncabezado {
    
    private string numSociedadField;
    
    private string numDivisionField;
    
    private string numProveedorField;
    
    private string correoField;
    
    private string monedaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumSociedad {
        get {
            return this.numSociedadField;
        }
        set {
            this.numSociedadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumDivision {
        get {
            return this.numDivisionField;
        }
        set {
            this.numDivisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumProveedor {
        get {
            return this.numProveedorField;
        }
        set {
            this.numProveedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Correo {
        get {
            return this.correoField;
        }
        set {
            this.correoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Moneda {
        get {
            return this.monedaField;
        }
        set {
            this.monedaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ahmsa.com/xsd/AddendaAHM1")]
public partial class AddendaAHMDocumentoDetalle {
    
    private AddendaAHMDocumentoDetallePedido[] pedidoField;
    
    private AddendaAHMDocumentoDetalleHojaServicio hojaServicioField;
    
    private AddendaAHMDocumentoDetalleTransporte transporteField;
    
    private AddendaAHMDocumentoDetalleCtaxPag ctaxPagField;
    
    private AddendaAHMDocumentoDetalleLiquidacion liquidacionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Pedido")]
    public AddendaAHMDocumentoDetallePedido[] Pedido {
        get {
            return this.pedidoField;
        }
        set {
            this.pedidoField = value;
        }
    }
    
    /// <remarks/>
    public AddendaAHMDocumentoDetalleHojaServicio HojaServicio {
        get {
            return this.hojaServicioField;
        }
        set {
            this.hojaServicioField = value;
        }
    }
    
    /// <remarks/>
    public AddendaAHMDocumentoDetalleTransporte Transporte {
        get {
            return this.transporteField;
        }
        set {
            this.transporteField = value;
        }
    }
    
    /// <remarks/>
    public AddendaAHMDocumentoDetalleCtaxPag CtaxPag {
        get {
            return this.ctaxPagField;
        }
        set {
            this.ctaxPagField = value;
        }
    }
    
    /// <remarks/>
    public AddendaAHMDocumentoDetalleLiquidacion Liquidacion {
        get {
            return this.liquidacionField;
        }
        set {
            this.liquidacionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ahmsa.com/xsd/AddendaAHM1")]
public partial class AddendaAHMDocumentoDetallePedido {
    
    private string[] recepcionField;
    
    private string numField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Recepcion", IsNullable=true)]
    public string[] Recepcion {
        get {
            return this.recepcionField;
        }
        set {
            this.recepcionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Num {
        get {
            return this.numField;
        }
        set {
            this.numField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ahmsa.com/xsd/AddendaAHM1")]
public partial class AddendaAHMDocumentoDetalleHojaServicio {
    
    private string numField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Num {
        get {
            return this.numField;
        }
        set {
            this.numField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ahmsa.com/xsd/AddendaAHM1")]
public partial class AddendaAHMDocumentoDetalleTransporte {
    
    private string numField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Num {
        get {
            return this.numField;
        }
        set {
            this.numField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ahmsa.com/xsd/AddendaAHM1")]
public partial class AddendaAHMDocumentoDetalleCtaxPag {
    
    private string numField;
    
    private string ejercicioField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Num {
        get {
            return this.numField;
        }
        set {
            this.numField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ejercicio {
        get {
            return this.ejercicioField;
        }
        set {
            this.ejercicioField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ahmsa.com/xsd/AddendaAHM1")]
public partial class AddendaAHMDocumentoDetalleLiquidacion {
    
    private string fechaInicioField;
    
    private string fechaFinField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FechaInicio {
        get {
            return this.fechaInicioField;
        }
        set {
            this.fechaInicioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FechaFin {
        get {
            return this.fechaFinField;
        }
        set {
            this.fechaFinField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ahmsa.com/xsd/AddendaAHM1")]
public partial class AddendaAHMDocumentoAnexos {
    
    private string anexoField;
    
    /// <remarks/>
    public string Anexo {
        get {
            return this.anexoField;
        }
        set {
            this.anexoField = value;
        }
    }
}
