//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace Iusacell
{


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.interfactura.com/Schemas/Documentos")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "https://www.interfactura.com/Schemas/Documentos", IsNullable = false)]
public partial class FacturaInterfactura
{

    private FacturaInterfacturaEmisor emisorField;

    private FacturaInterfacturaReceptor receptorField;

    private FacturaInterfacturaEncabezado encabezadoField;

    private t_TipoDocumento tipoDocumentoField;

    private System.Xml.XmlAttribute[] anyAttrField;

    /// <remarks/>
    public FacturaInterfacturaEmisor Emisor
    {
        get
        {
            return this.emisorField;
        }
        set
        {
            this.emisorField = value;
        }
    }

    /// <remarks/>
    public FacturaInterfacturaReceptor Receptor
    {
        get
        {
            return this.receptorField;
        }
        set
        {
            this.receptorField = value;
        }
    }

    /// <remarks/>
    public FacturaInterfacturaEncabezado Encabezado
    {
        get
        {
            return this.encabezadoField;
        }
        set
        {
            this.encabezadoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_TipoDocumento TipoDocumento
    {
        get
        {
            return this.tipoDocumentoField;
        }
        set
        {
            this.tipoDocumentoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.interfactura.com/Schemas/Documentos")]
public partial class FacturaInterfacturaEmisor
{

    private string riField;

    private System.Xml.XmlAttribute[] anyAttrField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RI
    {
        get
        {
            return this.riField;
        }
        set
        {
            this.riField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.interfactura.com/Schemas/Documentos")]
public partial class FacturaInterfacturaReceptor
{

    private string riField;

    private System.Xml.XmlAttribute[] anyAttrField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RI
    {
        get
        {
            return this.riField;
        }
        set
        {
            this.riField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.interfactura.com/Schemas/Documentos")]
public partial class FacturaInterfacturaEncabezado
{

    private FacturaInterfacturaEncabezadoCuerpo[] cuerpoField;

    private System.DateTime fechaField;

    private FacturaInterfacturaEncabezadoMonedaDoc monedaDocField;

    private FacturaInterfacturaEncabezadoIVAPCT iVAPCTField;

    private decimal ivaField;

    private decimal subTotalField;

    private decimal totalField;

    private System.DateTime fechaEntregaField;

    private string lugarEntregaField;

    private string lugarExpedicionField;

    private string condicionPagoField;

    private string numProveedorField;

    private string folioOrdenCompraField;

    private string observacionesField;

    private System.Xml.XmlAttribute[] anyAttrField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cuerpo")]
    public FacturaInterfacturaEncabezadoCuerpo[] Cuerpo
    {
        get
        {
            return this.cuerpoField;
        }
        set
        {
            this.cuerpoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime Fecha
    {
        get
        {
            return this.fechaField;
        }
        set
        {
            this.fechaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public FacturaInterfacturaEncabezadoMonedaDoc MonedaDoc
    {
        get
        {
            return this.monedaDocField;
        }
        set
        {
            this.monedaDocField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public FacturaInterfacturaEncabezadoIVAPCT IVAPCT
    {
        get
        {
            return this.iVAPCTField;
        }
        set
        {
            this.iVAPCTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Iva
    {
        get
        {
            return this.ivaField;
        }
        set
        {
            this.ivaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal SubTotal
    {
        get
        {
            return this.subTotalField;
        }
        set
        {
            this.subTotalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Total
    {
        get
        {
            return this.totalField;
        }
        set
        {
            this.totalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime FechaEntrega
    {
        get
        {
            return this.fechaEntregaField;
        }
        set
        {
            this.fechaEntregaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LugarEntrega
    {
        get
        {
            return this.lugarEntregaField;
        }
        set
        {
            this.lugarEntregaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LugarExpedicion
    {
        get
        {
            return this.lugarExpedicionField;
        }
        set
        {
            this.lugarExpedicionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CondicionPago
    {
        get
        {
            return this.condicionPagoField;
        }
        set
        {
            this.condicionPagoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumProveedor
    {
        get
        {
            return this.numProveedorField;
        }
        set
        {
            this.numProveedorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FolioOrdenCompra
    {
        get
        {
            return this.folioOrdenCompraField;
        }
        set
        {
            this.folioOrdenCompraField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Observaciones
    {
        get
        {
            return this.observacionesField;
        }
        set
        {
            this.observacionesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.interfactura.com/Schemas/Documentos")]
public partial class FacturaInterfacturaEncabezadoCuerpo
{

    private string renglonField;

    private decimal cantidadField;

    private string conceptoField;

    private decimal pUnitarioField;

    private decimal importeField;

    private string materialField;

    private string udeMField;

    private string numSerieField;

    private string observacionesField;

    private System.Xml.XmlAttribute[] anyAttrField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
    public string Renglon
    {
        get
        {
            return this.renglonField;
        }
        set
        {
            this.renglonField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Cantidad
    {
        get
        {
            return this.cantidadField;
        }
        set
        {
            this.cantidadField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Concepto
    {
        get
        {
            return this.conceptoField;
        }
        set
        {
            this.conceptoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal PUnitario
    {
        get
        {
            return this.pUnitarioField;
        }
        set
        {
            this.pUnitarioField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Importe
    {
        get
        {
            return this.importeField;
        }
        set
        {
            this.importeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Material
    {
        get
        {
            return this.materialField;
        }
        set
        {
            this.materialField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("U de M")]
    public string UdeM
    {
        get
        {
            return this.udeMField;
        }
        set
        {
            this.udeMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumSerie
    {
        get
        {
            return this.numSerieField;
        }
        set
        {
            this.numSerieField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Observaciones
    {
        get
        {
            return this.observacionesField;
        }
        set
        {
            this.observacionesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.interfactura.com/Schemas/Documentos")]
public enum FacturaInterfacturaEncabezadoMonedaDoc
{

    /// <remarks/>
    MXN,

    /// <remarks/>
    USD,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.interfactura.com/Schemas/Documentos")]
public enum FacturaInterfacturaEncabezadoIVAPCT
{

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("15")]
    Item15,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("10")]
    Item10,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.interfactura.com/Schemas/Documentos")]
public enum t_TipoDocumento
{

    /// <remarks/>
    Factura,
}

}