//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Xml.Schema;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://repository.edicomnet.com/schemas/mx/cfd/addenda")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://repository.edicomnet.com/schemas/mx/cfd/addenda", IsNullable=false)]
public partial class CinepolisRecepcion {


    [XmlAttribute("schemaLocation", Namespace = XmlSchema.InstanceNamespace)]
    public string xsiSchemaLocation = "http://repository.edicomnet.com/schemas/mx/cfd/addenda http://repository.edicomnet.com/schemas/mx/cfd/addenda/CinepolisRecepcion.xsd";


    private string idProveedorField;
    
    private string notaRecepcionField;
    
    private string contratoField;
    
    /// <remarks/>
    public string idProveedor {
        get {
            return this.idProveedorField;
        }
        set {
            this.idProveedorField = value;
        }
    }
    
    /// <remarks/>
    public string NotaRecepcion {
        get {
            return this.notaRecepcionField;
        }
        set {
            this.notaRecepcionField = value;
        }
    }
    
    /// <remarks/>
    public string Contrato {
        get {
            return this.contratoField;
        }
        set {
            this.contratoField = value;
        }
    }
}
