//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false, ElementName = "Documento")]
public partial class AddendaFemsa {
    
    private DocumentoFacturaFemsa facturaFemsaField;
    
    /// <remarks/>
    public DocumentoFacturaFemsa FacturaFemsa {
        get {
            return this.facturaFemsaField;
        }
        set {
            this.facturaFemsaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DocumentoFacturaFemsa {
    
    private decimal noVersAddField;
    
    private int claseDocField;
    
    private string noSociedadField;
    
    private string noProveedorField;
    
    private long noPedidoField;
    
    private string monedaField;
    
    private long noEntradaField;
    
    private string noRemisionField;
    
    private string noSocioField;
    
    private string centroField;
    
    private string iniPerLiqField;
    
    private string finPerLiqField;
    
    private string retencion1Field;
    
    private string retencion2Field;
    
    private string retencion3Field;
    
    private string emailField;
    
    private string datosAdicionalesField;
    
    private string tipoOperacionField;
    
    private string glfField;
    
    private string divisionField;
    
    private string asignacionField;
    
    private string cuentaField;
    
    private string cecoField;
    
    private string elementoPepField;
    
    /// <remarks/>
    public decimal noVersAdd {
        get {
            return this.noVersAddField;
        }
        set {
            this.noVersAddField = value;
        }
    }
    
    /// <remarks/>
    public int claseDoc {
        get {
            return this.claseDocField;
        }
        set {
            this.claseDocField = value;
        }
    }
    
    /// <remarks/>
    public string noSociedad {
        get {
            return this.noSociedadField;
        }
        set {
            this.noSociedadField = value;
        }
    }
    
    /// <remarks/>
    public string noProveedor {
        get {
            return this.noProveedorField;
        }
        set {
            this.noProveedorField = value;
        }
    }
    
    /// <remarks/>
    public long noPedido {
        get {
            return this.noPedidoField;
        }
        set {
            this.noPedidoField = value;
        }
    }
    
    /// <remarks/>
    public string moneda {
        get {
            return this.monedaField;
        }
        set {
            this.monedaField = value;
        }
    }
    
    /// <remarks/>
    public long noEntrada {
        get {
            return this.noEntradaField;
        }
        set {
            this.noEntradaField = value;
        }
    }
    
    /// <remarks/>
    public string noRemision {
        get {
            return this.noRemisionField;
        }
        set {
            this.noRemisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string noSocio {
        get {
            return this.noSocioField;
        }
        set {
            this.noSocioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string centro {
        get {
            return this.centroField;
        }
        set {
            this.centroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string iniPerLiq {
        get {
            return this.iniPerLiqField;
        }
        set {
            this.iniPerLiqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string finPerLiq {
        get {
            return this.finPerLiqField;
        }
        set {
            this.finPerLiqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string retencion1 {
        get {
            return this.retencion1Field;
        }
        set {
            this.retencion1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string retencion2 {
        get {
            return this.retencion2Field;
        }
        set {
            this.retencion2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string retencion3 {
        get {
            return this.retencion3Field;
        }
        set {
            this.retencion3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string datosAdicionales {
        get {
            return this.datosAdicionalesField;
        }
        set {
            this.datosAdicionalesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string tipoOperacion {
        get {
            return this.tipoOperacionField;
        }
        set {
            this.tipoOperacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string glf {
        get {
            return this.glfField;
        }
        set {
            this.glfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string division {
        get {
            return this.divisionField;
        }
        set {
            this.divisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string asignacion {
        get {
            return this.asignacionField;
        }
        set {
            this.asignacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string cuenta {
        get {
            return this.cuentaField;
        }
        set {
            this.cuentaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ceco {
        get {
            return this.cecoField;
        }
        set {
            this.cecoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string elementoPep {
        get {
            return this.elementoPepField;
        }
        set {
            this.elementoPepField = value;
        }
    }
}
