//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false, ElementName = "Disney")]
public partial class AddendaDisney {

    private DisneySupplierInformation supplierInformationField;

    private DisneyTransaction transactionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DisneySupplierInformation SupplierInformation
    {
        get
        {
            return this.supplierInformationField;
        }
        set
        {
            this.supplierInformationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DisneyTransaction Transaction
    {
        get
        {
            return this.transactionField;
        }
        set
        {
            this.transactionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DisneySupplierInformation {
    
    private string contactNameField;
    
    private string phoneNumberField;
    
    private string emailField;
    
    private string numberField;
    
    ///<summary>
    /// Nombre de la persona que será el contacto en la empresa proveedora
    /// </summary>
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ContactName {
        get {
            return this.contactNameField;
        }
        set {
            this.contactNameField = value;
        }
    }
    
    /// <summary>
    /// Teléfono del proveedor con clave Lada para marcarse desde el DF
    /// </summary>
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PhoneNumber {
        get {
            return this.phoneNumberField;
        }
        set {
            this.phoneNumberField = value;
        }
    }

    /// <summary>
    /// Correo electrónico del proveedor
    /// </summary>
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }

    /// <summary>
    /// Número de proveedor asignado por Disney
    /// </summary>
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DisneyTransaction {
    
    private string purchaseOrderField;
    
    private string goodReceiptField;
    
    private string casualBuyerEmailField;

    /// <summary>
    /// Número de órden de compra otrogada por Disney
    /// </summary>
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PurchaseOrder {
        get {
            return this.purchaseOrderField;
        }
        set {
            this.purchaseOrderField = value;
        }
    }
    
    /// <summary>
    /// Número de Good Receipt otorgado por Disney
    /// </summary>
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string GoodReceipt {
        get {
            return this.goodReceiptField;
        }
        set {
            this.goodReceiptField = value;
        }
    }
    
    /// <summary>
    /// Correo electrónico del comprador de Disney
    /// </summary>
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CasualBuyerEmail {
        get {
            return this.casualBuyerEmailField;
        }
        set {
            this.casualBuyerEmailField = value;
        }
    }
}
