//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Schema;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.axosnet.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.axosnet.com", IsNullable=false)]
public partial class ECFD {
    
    private ECFDOrdenDeCompra[] ordenDeCompraField;

    [XmlAttribute("schemaLocation", Namespace = XmlSchema.InstanceNamespace)]
    public string xsiSchemaLocation = "http://www.pagosxml.com.mx http://infoaddenda.pagosxml.com.mx/";
    
    private string versionField;
    
    private string noProveedorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OrdenDeCompra")]
    public ECFDOrdenDeCompra[] OrdenDeCompra {
        get {
            return this.ordenDeCompraField;
        }
        set {
            this.ordenDeCompraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string noProveedor {
        get {
            return this.noProveedorField;
        }
        set {
            this.noProveedorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.axosnet.com")]
public partial class ECFDOrdenDeCompra {
    
    private ECFDOrdenDeCompraPosicion[] posicionField;
    
    private string numeroField;
    
    private string monedaField;
    
    private string tipoCambioField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Posicion")]
    public ECFDOrdenDeCompraPosicion[] Posicion {
        get {
            return this.posicionField;
        }
        set {
            this.posicionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string numero {
        get {
            return this.numeroField;
        }
        set {
            this.numeroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string moneda {
        get {
            return this.monedaField;
        }
        set {
            this.monedaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tipoCambio {
        get {
            return this.tipoCambioField;
        }
        set {
            this.tipoCambioField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.axosnet.com")]
public partial class ECFDOrdenDeCompraPosicion {
    
    private string numeroField;
    
    private string materialField;
    
    private decimal cantidadField;
    
    private string unidadField;
    
    private decimal precioField;
    
    private decimal totalField;
    
    private string deliveryNoteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string numero {
        get {
            return this.numeroField;
        }
        set {
            this.numeroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string material {
        get {
            return this.materialField;
        }
        set {
            this.materialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal cantidad {
        get {
            return this.cantidadField;
        }
        set {
            this.cantidadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unidad {
        get {
            return this.unidadField;
        }
        set {
            this.unidadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal precio {
        get {
            return this.precioField;
        }
        set {
            this.precioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal total {
        get {
            return this.totalField;
        }
        set {
            this.totalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string deliveryNote {
        get {
            return this.deliveryNoteField;
        }
        set {
            this.deliveryNoteField = value;
        }
    }
}
